CREATE TABLE IF NOT EXISTS feeding_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date DATE NOT NULL,
    food TEXT,
    quantity VARCHAR(255),
    reaction VARCHAR(255),
    observations TEXT,
    CONSTRAINT feeding_entries_pkey PRIMARY KEY (id)
);
